# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alexander Gutierrez Portfolio
email: gutierrezalex@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Web Designer out of New York City.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://gutierreza.com" # the base hostname & protocol for your site
twitter_username: gutierrezalex
github_username: gutierrezalex
stackoverflow_username: "435811"

# Build settings
markdown: kramdown

# Clean URL path
permalink: /:title
